spring:
  jpa:
    show-sql: true
    properties:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
  #    hibernate:
  #      ddl-auto: validate
  datasource:
    driver-class name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boogle?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: ""
